### ISSUE TITLE
Error using sails-memory for tests

### ISSUE THREAD

**Issue by alexisHetic** [balderdashy/sails-memory#27]
Hi !

I'm trying to use sails-memory and Barrels to get some fixtures in my tests. 

I have created a model called Source and I got a fixture with one source. I can see that the source is in the sails memory, so I want to get the data to test it. I do : 
```javascript
Source.findOne(1, function(err, source) { console.log(source)};
```

And I get this Error : 

```javascript
Message:
    TypeError: Cannot read property 'select' of undefined
  Stack:
    TypeError: Cannot read property 'select' of undefined
        at Object.module.exports.adapter.find (/home/adrdra/.../node_modules/sails-memory/lib/adapter.js:117:27)
        at module.exports.find (/home/adrdra/.../node_modules/waterline/lib/waterline/adapter/dql.js:120:13)
        at module.exports.findOne (/home/adrdra/...t/node_modules/waterline/lib/waterline/adapter/dql.js:163:10)

...
```

**Comment by mattcodez** [comment]
I have a similar error when doing tests. After updating a model, I have a callback run a get() on the route but I receive an error:
```TypeError: Cannot read property 'getPKField' of undefined```
If I run the get() before on it's own, there is no problem. Both are identical routes. Not convinced it's sails-memory's fault but I'm not sure where to go from here.

**Comment by mattcodez** [comment]
So, I just randomly "fixed" this, but doesn't make much sense. I was running the callback via supertest's expect() callback. The call that was running it actually had a failing test that wasn't being reported. Once I fixed that, the callback runs as expected.
